const pointshopItems = [
    {
        id: 1,
        name: '배달의민족 10,000원 상품권',
        brand: '배달의민족',
        point: 10000,
        image: '/images/배달의민족_10k.jpg',
    },
    {
        id: 2,
        name: '배달의민족 30,000원 상품권',
        brand: '배달의민족',
        point: 30000,
        image: '/images/배달의민족_30k.jpg',
    },
    {
        id: 3,
        name: '배달의민족 50,000원 상품권',
        brand: '배달의민족',
        point: 50000,
        image: '/images/배달의민족_50k.jpg',
    },
    {
        id: 4,
        name: '올리브영 10,000원 상품권',
        brand: '올리브영',
        point: 10000,
        image: '/images/올리브영_10k.jpg',
    },
    {
        id: 5,
        name: '올리브영 30,000원 상품권',
        brand: '올리브영',
        point: 30000,
        image: '/images/올리브영_30k.jpg',
    },
    {
        id: 6,
        name: '올리브영 50,000원 상품권',
        brand: '올리브영',
        point: 50000,
        image: '/images/올리브영_50k.jpg',
    },
    {
        id: 7,
        name: '스타벅스 10,000원 상품권',
        brand: '스타벅스',
        point: 10000,
        image: '/images/스타벅스_10k.jpg',
    },
    {
        id: 8,
        name: '스타벅스 30,000원 상품권',
        brand: '스타벅스',
        point: 30000,
        image: '/images/스타벅스_30k.jpg',
    },
    {
        id: 9,
        name: '스타벅스 50,000원 상품권',
        brand: '스타벅스',
        point: 50000,
        image: '/images/스타벅스_50k.jpg',
    },
    {
        id: 10,
        name: '신세계 10,000원 상품권',
        brand: '신세계',
        point: 10000,
        image: '/images/신세계_10k.jpg',
    },
    {
        id: 11,
        name: '신세계 30,000원 상품권',
        brand: '신세계',
        point: 30000,
        image: '/images/신세계_30k.jpg',
    },
    {
        id: 12,
        name: '신세계 50,000원 상품권',
        brand: '신세계',
        point: 50000,
        image: '/images/신세계_50k.jpg',
    },
    {
        id: 13,
        name: '신세계 100,000원 상품권',
        brand: '신세계',
        point: 100000,
        image: '/images/신세계_100k.jpg',
    },
];

export default pointshopItems;
